/**
 * Commit Message Generator
 *
 * Utilities for generating, formatting, and parsing commit messages for PRs.
 * Used by PR Review Agent when approving PRs to store commit message for later merge.
 */

import { COMMIT_MESSAGE_MARKER } from '@/server/project-management/config';
import type { ProjectItemContent } from '@/server/project-management/types';

// ============================================================
// TYPES
// ============================================================

export interface PRInfo {
    title: string;
    body: string;
    additions: number;
    deletions: number;
    changedFiles: number;
    commits: number;
}

export interface CommitMessageResult {
    title: string;
    body: string;
}

export interface PhaseInfo {
    current: number;
    total: number;
}

// ============================================================
// COMMIT MESSAGE GENERATION
// ============================================================

/**
 * Generate commit message from PR info (deterministic, no AI)
 * Called by PR Reviewer when approving
 */
export function generateCommitMessage(
    prInfo: PRInfo,
    issueContent: ProjectItemContent | null,
    phaseInfo?: PhaseInfo
): CommitMessageResult {
    // Use PR title as commit title
    const title = prInfo.title;

    // Build commit body from PR info
    const body = buildCommitBody(prInfo, issueContent, phaseInfo);

    return { title, body };
}

/**
 * Build commit message body from PR info
 */
function buildCommitBody(
    prInfo: PRInfo,
    content: ProjectItemContent | null,
    phaseInfo?: PhaseInfo
): string {
    const lines: string[] = [];

    // Extract summary from PR body (before "---" separator or "## Test plan")
    const bodyParts = prInfo.body.split(/---|\n## Test [Pp]lan/);
    let summary = bodyParts[0].trim();

    // Remove "## Summary" header if present
    summary = summary.replace(/^## Summary\s*/i, '').trim();

    // Clean up bullet points - keep first 3 lines max
    const summaryLines = summary.split('\n').filter(line => line.trim()).slice(0, 3);
    if (summaryLines.length > 0) {
        lines.push(summaryLines.join('\n'));
    }

    // Add change stats
    lines.push('');
    lines.push(`Changes: +${prInfo.additions}/-${prInfo.deletions} across ${prInfo.changedFiles} files`);

    // Add phase info if multi-phase
    if (phaseInfo && phaseInfo.total > 1) {
        lines.push(`Phase: ${phaseInfo.current}/${phaseInfo.total}`);
    }

    // Add closes reference for final phase or single-phase
    if (content?.number) {
        const shouldClose = !phaseInfo || phaseInfo.current >= phaseInfo.total;
        if (shouldClose) {
            lines.push('');
            lines.push(`Closes #${content.number}`);
        } else {
            lines.push('');
            lines.push(`Part of #${content.number}`);
        }
    }

    return lines.join('\n');
}

// ============================================================
// PR COMMENT FORMATTING
// ============================================================

/**
 * Format commit message as a PR comment with marker
 */
export function formatCommitMessageComment(title: string, body: string): string {
    return `${COMMIT_MESSAGE_MARKER}
## Commit Message

This commit message will be used when merging this PR:

**Title:**
\`\`\`
${title}
\`\`\`

**Body:**
\`\`\`
${body}
\`\`\`

---
*Generated by PR Review Agent. Admin will use this when merging.*`;
}

/**
 * Parse commit message from PR comment
 */
export function parseCommitMessageComment(commentBody: string): CommitMessageResult | null {
    if (!commentBody.includes(COMMIT_MESSAGE_MARKER)) return null;

    // Extract title between first ``` pair after "Title:"
    const titleMatch = commentBody.match(/\*\*Title:\*\*\s*```\s*([\s\S]*?)```/);
    const bodyMatch = commentBody.match(/\*\*Body:\*\*\s*```\s*([\s\S]*?)```/);

    if (!titleMatch || !bodyMatch) return null;

    return {
        title: titleMatch[1].trim(),
        body: bodyMatch[1].trim(),
    };
}
